apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: internal-apps
  namespace: argo
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Internal Applications
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - "*"
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
    - namespace: "*"
      server: https://rancher.lauckserv.net/k8s/clusters/c-m-d25gnqct # prod
    - namespace: "*"
      server: https://rancher.lauckserv.net/k8s/clusters/c-m-klrcgt5t # tools
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
    - group: ""
      kind: NetworkPolicy
