apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-tool
  labels:
    lauckserv.io/category: cluster-tools
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
            lauckserv.io/external-secrets: "true"
  template:
    metadata:
      name: "{{ nameNormalized }}-external-secrets"
      labels:
        lauckserv.io/category: cluster-tools
    spec:
      project: cluster-tools
      source:
        repoURL: https://github.com/lauckserv/ops-infra-argo
        targetRevision: main
        path: "cluster-tools/tools/external-secrets"
        helm: {}
      destination:
        server: "{{ server }}"
        namespace: "external-secrets"
      ignoreDifferences:
        - group: "*"
          kind: "*"
          managedFieldsManagers:
            - external-secrets
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
