apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-application-sets
  labels:
    lauckserv.io/environment: production
    lauckserv.io/category: app
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  project: argocd
  source:
    path: applicationSets
    repoURL: https://github.com/lauckserv/ops-cluster-production
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
